### ISSUE TITLE
run.sh file cannot run.

### ISSUE THREAD

**Issue by ChaoTangTyson** [mrakotosaon/pointcleannet#1]
No such file or directory: './results\\galera100k_noise_white_1.00e-02_0.xyz'

I guess this is some path problem when I tried to run the denoise Network.

**Comment by mrakotosaon** [comment]
Hi @ChaoTangTyson , thank you for letting me know about this issue. You need to create a "results" directory in "noise_removal" directory. I updated the README accordingly.
