### ISSUE TITLE
[HELP WANTED] Simplified Inference

### ISSUE THREAD

**Issue by lucasamparo** [mrakotosaon/pointcleannet#11]
Could you help me to make a code to receive an point cloud and just output the denoised data, without any parametrization?

Just take a text file XYZ, pass trought the model, save the output as XYZ...

Thanks.

**Comment by mrakotosaon** [comment]
Hi @lucasamparo ,

For the denoising pipeline our script should already create a .xyz file given an input .xyz. And that for each iteration.
Are you refering to the outlier removal pipeline? In that case you can filter the .info file by selecting the first 3 columns by the value of the 4th column. We use a threshold of 0.5 in the 4th column to classify outliers.

Please don't hesitate if you have further questions.
Best,

Marie-Julie
