### ISSUE TITLE
LOSS

### ISSUE THREAD

**Issue by Majid-de** [mrakotosaon/pointcleannet#13]
hello,
i have a question, why are Losses so noisy and why can not they to be better than approximately 1,2
thank you

**Comment by Majid-de** [comment]
Hello,
another question, how can i evaluation a result of prediction a point cloud

**Comment by mrakotosaon** [comment]
Hi @Majid-de 

Unfortunately I do not have the exact loss values we got during the training of our models anymore. However, you should see a clear improvement in your training curves over time. If this is not the case maybe you need to train your model for a longer time? We did train ours for multiple days to write the paper. You might also get improvements by changing some training parameters.

For evaluation in the denoising application the main steps listed in the README should produce denoised point clouds:
cd noise_removal
mkdir results
./run.sh

Did you run into any issue with these steps?
