### ISSUE TITLE
about pre-trained model

### ISSUE THREAD

**Issue by ghost** [mrakotosaon/pointcleannet#14]
Hi, i'm studying about 3D vision via point cloud.
in point clean net, i want to run your pre trained model but there are two files each models "~model.pth" and "~params.pth".
i tried to run for my point data sets (69444, 6)

1.
model_outlier = torch.load("/content/PointCleanNetOutliers_model.pth")
model_outlier.eval()

model_denoise = torch.load("/content/Denoising/PointCleanNet_model.pth")
model_denoise.eval()

2.
model_outlier = torch.load("/content/PointCleanNetOutliers_params.pth")
model_outlier.eval()

model_denoise = torch.load("/content/Denoising/PointCleanNet_params.pth")
model_denoise.eval()

3.
model_outlier = torch.load("/content/PointCleanNetOutliers_model.pth")
model_outlier.load_state_dict(torch.load("/content/PointCleanNetOutliers_params.pth"))
model_outlier.eval()

model_denoise = torch.load("/content/Denoising/PointCleanNet_model.pth")
model_denoise.load_state_dict(torch.load("/content/PointCleanNet_params.pth"))
model_denoise.eval()

Nothing has been done...

can you tell me how?

i'm a beginner 🥲...

**Comment by mrakotosaon** [comment]
Hi @eunseoday 
Have you tried running the following in a terminal (this code is also in the read me)?
For outlier removal:
cd outliers_removal
mkdir results
python eval_pcpnet.py

For denoising:
cd noise_removal
mkdir results
./run.sh

Normally these run the pretrained model. If you want to run them separately and this works, you could then copy code from the eval_pcpnet.py files?
