### ISSUE TITLE
How to denoise point with jet-fitting method

### ISSUE THREAD

**Issue by ia-usami** [mrakotosaon/pointcleannet#15]
Hi, in this paper, it is said that the [jet fitting](https://dl.acm.org/doi/10.1145/1391989.1404582) method can be used to denoise point cloud. But the [example code](https://github.com/CGAL/cgal/tree/master/Jet_fitting_3/examples/Jet_fitting_3) does not show how to do it.
Can you give me more detail how to implement denoising with jet fitting method ? It would be great help for me.

**Comment by ghost** [comment]
Hi, how did you implement this?
It would be helpful to know that.
