### ISSUE TITLE
Seeking suggestions about tuning the hyper-parameters to handle larger point clouds

### ISSUE THREAD

**Issue by HeCraneChen** [mrakotosaon/pointcleannet#16]
Thanks for the amazing codebase. I'm trying to use your code on some real-world LiDAR point cloud, which is often of much larger scale than the data you tested here. (Let's say, the point cloud has 10~100 times more points than your example data.) There must be some hyper parameters to tune such as the patch size, right? 

Could you please provide some suggestions about in what way I should tune which parameters? (Don't want the code to run too slow, but also don't want to sacrifice too much accuracy)

Thanks!

**Comment by mrakotosaon** [comment]
Hi @HeCraneChen 
I don't think the current code is very optimized. Adding some parallel processing of the patches would definitely help in your case!
However tuning the patch size might affect the level of detail that you expect. Having a patch that is significantly larger might oversmooth the details that you get for instance.
Best,
