### ISSUE TITLE
I want to know codes of Evaluation Indicators

### ISSUE THREAD

**Issue by ghost** [mrakotosaon/pointcleannet#17]
This code does not include the evaluation measures used in the paper. (e.g., chamfer measure)
If you know evaluation methods, please add them to the code and explain them to us.
Best regards.

**Comment by mrakotosaon** [comment]
Hi @popopochan 
Unfortunately I don't have access to the chamfer measure code. However they should be reproducible with numpy using the equation in section 6.2 of the paper.
I would be happy to help if you have questions.
Best

**Comment by ghost** [comment]
Dear @mrakotosaon 
Thanks for the reply.
I have one more question, I am not sure if this is a good idea or not.
In the training dataset for the outlier removal task, the paper says 432 total. However, when I actually download the dataset, it seems to be only 162 total.
Am I understanding this incorrectly? I would appreciate it if you could tell me.
Thanks.
