### ISSUE TITLE
About fig.8 in the paper

### ISSUE THREAD

**Issue by ghost** [mrakotosaon/pointcleannet#18]
Dear @mrakotosaon 
What is the difference between the absolute chamfer measure and the relative chamfer measure in Figure 8?
It would be helpful if you could explain it using the equation of the chamfer measure in the paper.
Also, what are the indicators of precession and recall (TP and FP) conditions when calculating the f1 score?
I would appreciate it if you could tell me.
Thanks.

**Comment by mrakotosaon** [comment]
Dear @ghost ,

Sorry for the delay, in case this can still help: the relative chamfer measure in Figure 8 is the chamfer value normalized by ours so c(P, .)/c(P, P_ours).

Thank you
