### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by liasy-0** [mrakotosaon/pointcleannet#19]
Dear author, may I ask how the visualization in Figure 7 of your paper is displayed? Looking forward to your reply, thank you very much

**Comment by mrakotosaon** [comment]
Dear @liasy-0 ,
Unfortunately I do not have access to the code I used to generate this figure anymore. Some alternatives could be this blender toolbox https://github.com/HTDerekLiu/BlenderToolbox or https://polyscope.run/py/ .

Best,
