### ISSUE TITLE
How Can I check the result for noise removal?

### ISSUE THREAD

**Issue by ChaoTangTyson** [mrakotosaon/pointcleannet#2]
And  If I want to use my own model to denoise with your noise removal model, how can I do that?
 I didnt find where you input the data of gelera and where is your output. can you tell me about that ?

**Comment by mrakotosaon** [comment]
Hi @ChaoTangTyson , the input and output data paths are specified by the "indir" and "outdir" options of the file "eval_pcpnet.py" in the "outliers_removal" directory. By default, they are set to: "data/pointCleanNetOutliersTestSet" and "results" directories respectively. The list of the shapes you want to process should be specified in the "validationset.txt" file in the input data directory.
