### ISSUE TITLE
Train your own dataset

### ISSUE THREAD

**Issue by seeflowersea** [mrakotosaon/pointcleannet#20]
Hello, I want to train my own dataset how to work?

**Comment by mrakotosaon** [comment]
Hi @seeflowersea 
You will need to save corresponding clean and noisy point clouds in separate files with the same prefix like in our dataset here: https://nuage.lix.polytechnique.fr/index.php/s/xSRrTNmtgqgeLGa .

**Comment by NiuYingchun** [comment]
Is it important to train on your own dataset with the same number of point cloud points input to the network? We have done the training on denoising with our own dataset, but the inference has a dimension mismatch, do you think it is a problem of inconsistent number of point cloud points. Finally, thank you for such a pioneering work.

**Comment by mrakotosaon** [comment]
During training all the patches need to have the same amount of points. When not possible we pad with zero values.
