### ISSUE TITLE
The default  parameter sym_op (symmetric operation) is 'max '

### ISSUE THREAD

**Issue by only-tao** [mrakotosaon/pointcleannet#22]
Hello, I want to know why the 'sym_op' in  your code is 'max' but not 'sum'  in your paper? Thank you so much for your answer.
If it' s my negligence, I'm so sorry to say that.
![截图 2023-12-18 21-40-46](https://github.com/mrakotosaon/pointcleannet/assets/54075362/80248bd4-719e-4d65-b71a-d68dfebc99ca)

**Comment by mrakotosaon** [comment]
Hi @only-tao 

Thank you for your message. You can choose the operator sym_op as an argument of the training command. I think sum and max both lead to similar results results in practice.
