### ISSUE TITLE
PointCleanNet does not export "normal" and "xyz" file?

### ISSUE THREAD

**Issue by linlinge** [mrakotosaon/pointcleannet#4]
When I run PointCleanNet with my own dataset, it just export ".info" file but missing the "normal" and "xyz" file.

**Comment by mrakotosaon** [comment]
Hi @linlinge ,

For outliers removal the output is a file .info that contains the xyz coordinates in the first 3 columns and the outlier label in the 4th column. We decide that a point is an outlier if that value is larger than 0.5. We do not regenerate the xyz file for the task of outlier removal.

**Comment by linlinge** [comment]
Thanks for your reply! I will try it again with your recommand threshold.

**Comment by Hao-HUST** [comment]
> Hi @linlinge ,
> 
> For outliers removal the output is a file .info that contains the xyz coordinates in the first 3 columns and the outlier label in the 4th column. We decide that a point is an outlier if that value is larger than 0.5. We do not regenerate the xyz file for the task of outlier removal.

Hi, @mrakotosaon.

How to visualize the outlier remove result(the .info file)?

**Comment by Hao-HUST** [comment]
> > Hi @linlinge ,
> > For outliers removal the output is a file .info that contains the xyz coordinates in the first 3 columns and the outlier label in the 4th column. We decide that a point is an outlier if that value is larger than 0.5. We do not regenerate the xyz file for the task of outlier removal.
> 
> Hi, @mrakotosaon.
> 
> How to visualize the outlier remove result(the .info file)?

Oh, the .info file(outlier result) can be visualized by the software of cloud compare, and the outlier labels can be treated as the scalar field value. 

It is easy to separate the outlier and inlier point cloud by setting a scalar threshold.

**Comment by mrakotosaon** [comment]
Hi @Hao-HUST 
That's nice to hear! :)
Another possibility would also be to filter the file with a small python script if you want a permanently filtered file.
Best,
