### ISSUE TITLE
Deal with ten milion point cloud very slow

### ISSUE THREAD

**Issue by linlinge** [mrakotosaon/pointcleannet#5]
when I remove outliers using default setting for my point cloud with more than 10 milion points, the PointCleanNet runs slowly, it will spend several days to complete this task. I was confused why it is so slow while using the default network model?

**Comment by mrakotosaon** [comment]
Hi @linlinge ,
Since PointCleanNet processes patches centered at each point at a time it can indeed be slow. 
Maybe you can use a larger batch size to accelerate the processing of your point cloud?

**Comment by linlinge** [comment]
Thank your for your answer! Yes, I have changed the batch size to 32, but my graphics card (gtx 1660 super) is not enough powerful, when I change it to a larger value, it will crash because of insufficient memory.
