### ISSUE TITLE
Mesh files

### ISSUE THREAD

**Issue by luost26** [mrakotosaon/pointcleannet#8]
Hi, 

Could you provide the mesh files of the point clouds? Thank you!

**Comment by mrakotosaon** [comment]
Hi @luost26 ,

Please find here a link to the original meshes: [https://nuage.lix.polytechnique.fr/index.php/s/9CrHe259zaJEMb8/download](https://nuage.lix.polytechnique.fr/index.php/s/9CrHe259zaJEMb8/download) 

Best,

Marie-Julie

**Comment by luost26** [comment]
Thank you so much. This is very helpful!
