### ISSUE TITLE
Output outlier file has ALL the points present in an input file while running the eval_pcpnet.py

### ISSUE THREAD

**Issue by vigneshr2306** [mrakotosaon/pointcleannet#9]
If I run the eval_pcpnet.py in outliers removal for a file, say box_push100k.xyz which has 100k points, the resulting outlier file is having the same 100k points as outliers, which does not make sense to me. Can someone explain why this is happening?

**Comment by mrakotosaon** [comment]
Hi @vigneshr2306 ,
The code should produce a ".info" file as well. That file contains the xyz coordinates but also the output of the network as the 4th column which is a number between 0  and 1 which you can use to filter outliers (using the threshold of 0.5). It is useful if you want to keep track of the correspondence between old and filtered points.
Best,

**Comment by vigneshr2306** [comment]
Thanks for replying.
This works with the dataset provided by you, but when I'm using a dataset of my own, for example, a roof classification dataset (RoofN3D), **the entire 4th column shows values like 0.98 for all the points**. Why is that happening? (It is to note that my roof data points are lesser in number, 300 points per file)

![pointcleannet](https://user-images.githubusercontent.com/67469638/99420470-40a3c180-2923-11eb-81f4-3859b84070ae.PNG)

**Comment by mrakotosaon** [comment]
You might need to adjust the patch size and number of points per patch to approximate the context of the training. For example we had 5% of the point cloud bbox diagonal on 100k point clouds for training. We also had 500 points per patch for training.
One solution might be to retrain on your dataset. Or increase the patch size.
